name: mobil_store_web
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_image_slideshow: ^0.1.6
  firebase_core: ^2.24.2
  carousel_slider: ^4.2.1
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/
